#是否将自己注册到Eureka Server，默认为true，由于当前就是server，所以设成false，表明该服务不会向Eureka注册自己的信息
eureka:
  client:
    register-with-eureka: true
#是否从Eureka Server获取注册信息，由于是单节点，不需要同步其他节点数据，false
    fetch-registry: true
#设置服务注册中心的URL，用于client和server端交流。要在hosts文件中配置eureka-7900
    service-url:
      defaultZone: http://lisz:123@eureka-7900:7900/eureka/
  instance:
    hostname: eureka-7901
    prefer-ip-address: false

server:
  port: 7901

spring:
  application:
    name: Eureka
  boot:
    admin:
      client:
        url: http://192.168.1.102:8080

# springboot admin配置，pom添加依赖后要加上这个
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always