#是否将自己注册到Eureka Server，默认为true，由于当前就是server，所以设成false，表明该服务不会向Eureka注册自己的信息
eureka:
  client:
    register-with-eureka: true
#是否从Eureka Server获取注册信息，由于是单节点，不需要同步其他节点数据，false
    fetch-registry: true
#设置服务注册中心的URL，用于client和server端交流. 设定向哪里注册，可以写多个地址，只有这里是别的机器的地址。要在hosts文件中配置eureka-7901
    service-url:
      defaultZone: http://lisz:123@eureka-7901:7901/eureka/
  instance:
    # hostname是用来查找主机的
    hostname: eureka-7900
    prefer-ip-address: false

server:
  port: 7900

#application name 的是一样的。通过服务名去标志分组寻找服务的 eureka.instance.appname和下面的效果是一样的
spring:
  application:
    name: Eureka