
spring:
  application:
    name: zuul-test
    # springboot admin配置，pom添加依赖后要加上这个，上报至某个url
  boot:
    admin:
      client:
        url: http://192.168.1.102:8080
  zipkin:
    # 每个微服务都向这个地址上报信息
    base-url: http://192.168.1.102:9411
  sleuth:
    sampler:
      rate: 1
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://lisz:123@eureka-7900:7900/eureka/,http://lisz:123$eureka-7901:7901/eureka/
# 负载均衡策略配置为随机，而不是默认的"轮询"
user-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    routes:
      enabled: true
zuul:
  routes:
    xx:
      path: /xx/**
      url: https://github.com/lisz1012